BEGIN;
SELECT plan(8);
INSERT INTO public.stripe_events(event_id,event_type,received_at) VALUES('evt_synthetic_retention_0','synthetic',clock_timestamp()-interval '200 days');
INSERT INTO private.lifecycle_work(kind,dedupe_key,resource_id,action,state,claim_token,lease_until,completed_at,created_at) VALUES('stripe_event','evt_synthetic_retention_0','evt_synthetic_retention_0','synthetic','received',NULL,NULL,NULL,clock_timestamp()-interval '200 days');
DELETE FROM public.stripe_events WHERE event_id='evt_synthetic_retention_0';
SELECT is((SELECT count(*)::INTEGER FROM public.stripe_events WHERE event_id='evt_synthetic_retention_0'),1,'received age 120 retention eligibility');
INSERT INTO public.stripe_events(event_id,event_type,received_at) VALUES('evt_synthetic_retention_1','synthetic',clock_timestamp()-interval '200 days');
INSERT INTO private.lifecycle_work(kind,dedupe_key,resource_id,action,state,claim_token,lease_until,completed_at,created_at) VALUES('stripe_event','evt_synthetic_retention_1','evt_synthetic_retention_1','synthetic','processing',gen_random_uuid(),clock_timestamp()+interval '1 minute',NULL,clock_timestamp()-interval '200 days');
DELETE FROM public.stripe_events WHERE event_id='evt_synthetic_retention_1';
SELECT is((SELECT count(*)::INTEGER FROM public.stripe_events WHERE event_id='evt_synthetic_retention_1'),1,'processing age 120 retention eligibility');
INSERT INTO public.stripe_events(event_id,event_type,received_at) VALUES('evt_synthetic_retention_2','synthetic',clock_timestamp()-interval '200 days');
INSERT INTO private.lifecycle_work(kind,dedupe_key,resource_id,action,state,claim_token,lease_until,completed_at,created_at) VALUES('stripe_event','evt_synthetic_retention_2','evt_synthetic_retention_2','synthetic','retryable',NULL,NULL,NULL,clock_timestamp()-interval '200 days');
DELETE FROM public.stripe_events WHERE event_id='evt_synthetic_retention_2';
SELECT is((SELECT count(*)::INTEGER FROM public.stripe_events WHERE event_id='evt_synthetic_retention_2'),1,'retryable age 120 retention eligibility');
INSERT INTO public.stripe_events(event_id,event_type,received_at) VALUES('evt_synthetic_retention_3','synthetic',clock_timestamp()-interval '200 days');
INSERT INTO private.lifecycle_work(kind,dedupe_key,resource_id,action,state,claim_token,lease_until,completed_at,created_at) VALUES('stripe_event','evt_synthetic_retention_3','evt_synthetic_retention_3','synthetic','waiting',NULL,NULL,NULL,clock_timestamp()-interval '200 days');
DELETE FROM public.stripe_events WHERE event_id='evt_synthetic_retention_3';
SELECT is((SELECT count(*)::INTEGER FROM public.stripe_events WHERE event_id='evt_synthetic_retention_3'),1,'waiting age 120 retention eligibility');
INSERT INTO public.stripe_events(event_id,event_type,received_at) VALUES('evt_synthetic_retention_4','synthetic',clock_timestamp()-interval '200 days');
INSERT INTO private.lifecycle_work(kind,dedupe_key,resource_id,action,state,claim_token,lease_until,completed_at,created_at) VALUES('stripe_event','evt_synthetic_retention_4','evt_synthetic_retention_4','synthetic','blocked',NULL,NULL,NULL,clock_timestamp()-interval '200 days');
DELETE FROM public.stripe_events WHERE event_id='evt_synthetic_retention_4';
SELECT is((SELECT count(*)::INTEGER FROM public.stripe_events WHERE event_id='evt_synthetic_retention_4'),1,'blocked age 120 retention eligibility');
INSERT INTO public.stripe_events(event_id,event_type,received_at) VALUES('evt_synthetic_retention_5','synthetic',clock_timestamp()-interval '200 days');
INSERT INTO private.lifecycle_work(kind,dedupe_key,resource_id,action,state,claim_token,lease_until,completed_at,created_at) VALUES('stripe_event','evt_synthetic_retention_5','evt_synthetic_retention_5','synthetic','dead_letter',NULL,NULL,NULL,clock_timestamp()-interval '200 days');
DELETE FROM public.stripe_events WHERE event_id='evt_synthetic_retention_5';
SELECT is((SELECT count(*)::INTEGER FROM public.stripe_events WHERE event_id='evt_synthetic_retention_5'),1,'dead_letter age 120 retention eligibility');
INSERT INTO public.stripe_events(event_id,event_type,received_at) VALUES('evt_synthetic_retention_6','synthetic',clock_timestamp()-interval '200 days');
INSERT INTO private.lifecycle_work(kind,dedupe_key,resource_id,action,state,claim_token,lease_until,completed_at,created_at) VALUES('stripe_event','evt_synthetic_retention_6','evt_synthetic_retention_6','synthetic','completed',NULL,NULL,clock_timestamp()-interval '89 days',clock_timestamp()-interval '200 days');
DELETE FROM public.stripe_events WHERE event_id='evt_synthetic_retention_6';
SELECT is((SELECT count(*)::INTEGER FROM public.stripe_events WHERE event_id='evt_synthetic_retention_6'),1,'completed age 89 retention eligibility');
INSERT INTO public.stripe_events(event_id,event_type,received_at) VALUES('evt_synthetic_retention_7','synthetic',clock_timestamp()-interval '200 days');
INSERT INTO private.lifecycle_work(kind,dedupe_key,resource_id,action,state,claim_token,lease_until,completed_at,created_at) VALUES('stripe_event','evt_synthetic_retention_7','evt_synthetic_retention_7','synthetic','completed',NULL,NULL,clock_timestamp()-interval '91 days',clock_timestamp()-interval '200 days');
DELETE FROM public.stripe_events WHERE event_id='evt_synthetic_retention_7';
SELECT is((SELECT count(*)::INTEGER FROM public.stripe_events WHERE event_id='evt_synthetic_retention_7'),0,'completed age 91 retention eligibility');
SELECT * FROM finish();
ROLLBACK;
