export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'wip',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'app',
        'workers',
        'api',
        'ui',
        'tasks',
        'hideout',
        'maps',
        'team',
        'settings',
        'admin',
        'i18n',
        'deps',
        'config',
        'ci',
      ],
    ],
    'subject-case': [2, 'never', ['upper-case']],
    'header-max-length': [2, 'always', 100],
  },
};
