files:
  - source: /app/locales/en.json
    translation: /app/locales/%two_letters_code%.json
    update_option: update_as_unapproved
    export_languages:
      - de
      - es
      - fr
      - ru
      - uk
      - zh
